GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content" : "Learning backend while using Postman to check endpoints",
    "important" : true
}